# Site settings
title: Short time
tag_text: About
description: Personal website of Ankit Baruah, final year student majoring in Computer Science. Class of 2018 at IIT Kharagpur.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
